# frozen_string_literal: true

source "https://rubygems.org"
gemspec

gem "rails", ">= 7", "< 7.1"

gem "rails-dummy", github: "robotex82/rails-dummy", branch: "feature/ruby-3-2-compatibility"

git "https://github.com/beegoodit/bgit-ruby" do
  gem "bgit-frontend_auth" # , path: "~/projects/gems/bgit-ruby/bgit-frontend_auth"
  gem "bgit-invoicing" # , path: "~/projects/gems/bgit-ruby/bgit-invoicing"
end

git "https://github.com/content-management-on-rails/cmor", branch: "main" do
  gem "cmor-core-settings" # , path: "~/projects/gems/cmor/cmor-core-settings"
  gem "cmor-core-backend" # , path: "~/projects/gems/cmor/cmor-core-backend"
  gem "cmor-core" # , path: "~/projects/gems/cmor/cmor-core"
  gem "cmor" # , path: "~/projects/gems/cmor"
end

git "https://github.com/content-management-on-rails/cmor-translations" do
  gem "cmor-translations" # , path: "~/projects/gems/cmor-translations"
end

git "https://github.com/beegoodit/lexoffice-ruby" do
  gem "lexoffice_client" # , path: "~/projects/gems/lexoffice-ruby/lexoffice_client"
  gem "lexoffice_client-rails" # , path: "~/projects/gems/lexoffice-ruby/lexoffice_client-rails"
end

git "https://github.com/robotex82/json_seeds-rails" do
  gem "json_seeds-rails" # , path: "~/projects/gems/json_seeds-rails"
end

gem "simple_form-fake_inputs", git: "https://github.com/robotex82/simple_form-fake_inputs"
gem "timeline_events", git: "https://github.com/robotex82/timeline_events"
