# frozen_string_literal: true

source "https://rubygems.org"
gemspec
gem "simple_form-fake_inputs", git: "https://github.com/robotex82/simple_form-fake_inputs"
gem "timeline_events", git: "https://github.com/robotex82/timeline_events"
gem "cmor-translations", git: "https://github.com/content-management-on-rails/cmor-translations"
gem "rails-dummy", git: "https://github.com/robotex82/rails-dummy"
gem "rails", "6.1.4"