source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

gem "tfc-mdm", path: "../tfc-mdm"
gem "cmor", git: "https://github.com/content-management-on-rails/cmor", branch: "feature/cmor-core-api"
gem "cmor_core", git: "https://github.com/content-management-on-rails/cmor", branch: "feature/cmor-core-api", glob: "cmor_core/*.gemspec"
gem "cmor-core-api", git: "https://github.com/content-management-on-rails/cmor", branch: "feature/cmor-core-api", glob: "cmor-core-api/*.gemspec"
gem "simple_form-fake_inputs", git: "https://github.com/robotex82/simple_form-fake_inputs"
gem "timeline_events", git: "https://github.com/robotex82/timeline_events"
gem "cmor-translations", git: "https://github.com/content-management-on-rails/cmor-translations"
gem "rao-api-resources_controller", path: "~/projects/gems/rao/rao-api-resources_controller"
gem "rao-api-service_controller", path: "~/projects/gems/rao/rao-api-service_controller"
gem "rao-query", path: "~/projects/gems/rao/rao-query"
gem "rails-dummy", github: "robotex82/rails-dummy", branch: "feature/ruby-3-2-compatibility"
gem "rails", ">= 7"
