source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

gem "rao-api-resources_controller", path: "~/projects/gems/rao/rao-api-resources_controller"
gem "rao-api-service_controller", path: "~/projects/gems/rao/rao-api-service_controller"
gem "rao-query", path: "~/projects/gems/rao/rao-query"
