require "bundler/setup"

APP_RAKEFILE = File.expand_path("spec/dummy/Rakefile", __dir__)
if File.exist?(APP_RAKEFILE)
  load "rails/tasks/engine.rake"
end

load "rails/tasks/statistics.rake"

require "bundler/gem_tasks"

require 'rails/dummy/tasks'