source "https://rubygems.org"
gemspec

gem "tfc-mdm", path: "../tfc-mdm"

git "https://github.com/beegoodit/bgit-ruby" do
  gem "bgit-frontend_auth" # , path: "~/projects/gems/bgit-ruby/bgit-frontend_auth"
  gem "bgit-invoicing" # , path: "~/projects/gems/bgit-ruby/bgit-invoicing"
end

git "https://github.com/content-management-on-rails/cmor-translations" do
  gem "cmor-translations" # , path: "~/projects/gems/cmor-translations"
end
gem "rails-dummy", github: "robotex82/rails-dummy", branch: "feature/ruby-3-2-compatibility"

git "https://github.com/content-management-on-rails/cmor", branch: "main" do
  gem "cmor-core-settings"
  gem "cmor-core-backend"
  gem "cmor-core"
  gem "cmor"
end

gem "json_seeds-rails", git: "https://github.com/robotex82/json_seeds-rails"
gem "simple_form-fake_inputs", git: "https://github.com/robotex82/simple_form-fake_inputs"
gem "timeline_events", git: "https://github.com/robotex82/timeline_events"
gem "country_select", git: "https://github.com/countries/country_select"