# frozen_string_literal: true

source "https://rubygems.org"
gemspec

gem 'tfc-mdm', path: '../tfc-mdm'
gem "simple_form-fake_inputs", git: "https://github.com/robotex82/simple_form-fake_inputs"
gem "timeline_events", git: "https://github.com/robotex82/timeline_events"
gem "cmor-translations", git: "https://github.com/content-management-on-rails/cmor-translations"
gem "rails-dummy", github: "robotex82/rails-dummy", branch: "feature/ruby-3-2-compatibility"
gem "rails", "6.1.4"